class Main {
    public static void main(String[] args)
    {
        String str = "Kaviya";
        int Tamil = 78;
        int English = 80;
        int Maths = 66;
        int Science = 78;
        int Social = 90;
         System.out.println("Name="+str);
         System.out.println("Tamil="+Tamil);
         System.out.println("English="+English);
         System.out.println("Maths="+Maths);
         System.out.println("Scienc="+Science);
         System.out.println("Social="+Social);
         
    }
}
